# coding: utf-8

"""
    Schedule OpenApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.return_user_actual_schedule import ReturnUserActualSchedule

class TestReturnUserActualSchedule(unittest.TestCase):
    """ReturnUserActualSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReturnUserActualSchedule:
        """Test ReturnUserActualSchedule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReturnUserActualSchedule`
        """
        model = ReturnUserActualSchedule()
        if include_optional:
            return ReturnUserActualSchedule(
                name_medication = ''
            )
        else:
            return ReturnUserActualSchedule(
                name_medication = '',
        )
        """

    def testReturnUserActualSchedule(self):
        """Test ReturnUserActualSchedule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
