# coding: utf-8

"""
    Schedule OpenApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_next_takings_get(self) -> None:
        """Test case for next_takings_get

        Получение актуального расписания пользователю (По умолчанию на час вперёд)
        """
        pass

    def test_schedule_get(self) -> None:
        """Test case for schedule_get

        Получение конкретного расписания
        """
        pass

    def test_schedule_post(self) -> None:
        """Test case for schedule_post

        Добавление расписания приёма лекарств для пользователя
        """
        pass

    def test_schedules_get(self) -> None:
        """Test case for schedules_get

        Получение всех расписаний приёма лекарств пользователя
        """
        pass


if __name__ == '__main__':
    unittest.main()
