# coding: utf-8

"""
    Schedule OpenApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schedule_get400_response import ScheduleGet400Response

class TestScheduleGet400Response(unittest.TestCase):
    """ScheduleGet400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleGet400Response:
        """Test ScheduleGet400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleGet400Response`
        """
        model = ScheduleGet400Response()
        if include_optional:
            return ScheduleGet400Response(
                error = '',
                details = ''
            )
        else:
            return ScheduleGet400Response(
        )
        """

    def testScheduleGet400Response(self):
        """Test ScheduleGet400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
