# coding: utf-8

"""
    Schedule OpenApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_return_schedule_data import UserReturnScheduleData

class TestUserReturnScheduleData(unittest.TestCase):
    """UserReturnScheduleData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserReturnScheduleData:
        """Test UserReturnScheduleData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserReturnScheduleData`
        """
        model = UserReturnScheduleData()
        if include_optional:
            return UserReturnScheduleData(
                name_medication = '',
                first_day = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                limitation_days = 1,
                daily_schedule = [
                    ''
                    ]
            )
        else:
            return UserReturnScheduleData(
                name_medication = '',
                first_day = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                daily_schedule = [
                    ''
                    ],
        )
        """

    def testUserReturnScheduleData(self):
        """Test UserReturnScheduleData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
