from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SchedulePost400Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error=None, details=None):  # noqa: E501
        """SchedulePost400Response - a model defined in OpenAPI

        :param error: The error of this SchedulePost400Response.  # noqa: E501
        :type error: str
        :param details: The details of this SchedulePost400Response.  # noqa: E501
        :type details: str
        """
        self.openapi_types = {
            'error': str,
            'details': str
        }

        self.attribute_map = {
            'error': 'error',
            'details': 'details'
        }

        self._error = error
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'SchedulePost400Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _schedule_post_400_response of this SchedulePost400Response.  # noqa: E501
        :rtype: SchedulePost400Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> str:
        """Gets the error of this SchedulePost400Response.

        Описание ошибки  # noqa: E501

        :return: The error of this SchedulePost400Response.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this SchedulePost400Response.

        Описание ошибки  # noqa: E501

        :param error: The error of this SchedulePost400Response.
        :type error: str
        """

        self._error = error

    @property
    def details(self) -> str:
        """Gets the details of this SchedulePost400Response.

        Детали ошибки  # noqa: E501

        :return: The details of this SchedulePost400Response.
        :rtype: str
        """
        return self._details

    @details.setter
    def details(self, details: str):
        """Sets the details of this SchedulePost400Response.

        Детали ошибки  # noqa: E501

        :param details: The details of this SchedulePost400Response.
        :type details: str
        """

        self._details = details
