openapi: 3.0.0

info:
  title: Schedule OpenApi
  version: "1.0.0"

servers:
  - url: http://localhost:5000
    description: Main server

paths:
  /schedule:
    post:
      summary: Добавление расписания приёма лекарств для пользователя
      description: Создает новое расписание приема лекарств для указанного пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataOfUserRequest'
      responses:
        '201':
          description: Расписание успешно создано
          content:
            application/json:
              schema:
                type: object
                nullable: true
        '400':
          description: Некорректные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /schedules:
    get:
      summary: Получение всех расписаний приёма лекарств пользователя
      description: Возвращает все расписания пользователя
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            format: int32
          description: ID пользователя
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserReturnScheduleData'
        '400':
          description: Некорректные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Расписание не найдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /next_takings:
    get:
      summary: Получение актуального расписания пользователю
      description: Получение актуального расписания по user_id (по умолчанию на час вперёд)
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            format: int32
          description: ID пользователя
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReturnUserActualSchedule'
        '400':
          description: Некорректные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Расписание не найдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    DataOfUserRequest:
      type: object
      required:
        - user_id
        - name_pills
        - limitation_days
        - number_iters
      properties:
        user_id:
          type: integer
          format: int32
          example: 123
        name_pills:
          type: string
          example: "Аспирин"
        limitation_days:
          type: integer
          format: int32
          minimum: 1
          example: 7
        number_iters:
          type: integer
          format: int32
          minimum: 1
          example: 2

    UserReturnScheduleData:
      type: object
      properties:
        name_medication:
          type: string
          example: "Аспирин"
        first_day:
          type: string
          format: date
          example: "2023-01-01"
        last_day:
          type: string
          format: date
          nullable: true
          example: "2023-01-07"
        daily_schedule:
          type: array
          items:
            type: string
            format: time
          example: ["08:00", "20:00"]

    ReturnUserActualSchedule:
      type: object
      properties:
        name_medication:
          type: string
          example: "Аспирин"
        next_taking_time:
          type: string
          format: date-time
          example: "2023-01-01T08:00:00Z"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid request data"
        details:
          type: string
          nullable: true
          example: "User ID must be positive integer"