# coding: utf-8

# flake8: noqa

"""
    Schedule OpenApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.data_of_user_request import DataOfUserRequest
from openapi_client.models.return_user_actual_schedule import ReturnUserActualSchedule
from openapi_client.models.schedule_get200_response import ScheduleGet200Response
from openapi_client.models.schedule_get400_response import ScheduleGet400Response
from openapi_client.models.schedule_get404_response import ScheduleGet404Response
from openapi_client.models.schedule_get500_response import ScheduleGet500Response
from openapi_client.models.schedule_post400_response import SchedulePost400Response
from openapi_client.models.user_return_schedule_data import UserReturnScheduleData
