# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gRPC import schedule_pb2 as gRPC_dot_schedule__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gRPC/schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScheduleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSchedule = channel.unary_unary(
                '/schedule.ScheduleService/AddSchedule',
                request_serializer=gRPC_dot_schedule__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=gRPC_dot_schedule__pb2.ScheduleResponse.FromString,
                _registered_method=True)
        self.GetSchedule = channel.unary_unary(
                '/schedule.ScheduleService/GetSchedule',
                request_serializer=gRPC_dot_schedule__pb2.GetScheduleRequest.SerializeToString,
                response_deserializer=gRPC_dot_schedule__pb2.GetScheduleResponse.FromString,
                _registered_method=True)
        self.GetSchedules = channel.unary_unary(
                '/schedule.ScheduleService/GetSchedules',
                request_serializer=gRPC_dot_schedule__pb2.GetSchedulesRequest.SerializeToString,
                response_deserializer=gRPC_dot_schedule__pb2.GetSchedulesResponse.FromString,
                _registered_method=True)
        self.GetNextTakings = channel.unary_unary(
                '/schedule.ScheduleService/GetNextTakings',
                request_serializer=gRPC_dot_schedule__pb2.NextTakingsRequest.SerializeToString,
                response_deserializer=gRPC_dot_schedule__pb2.NextTakingsResponse.FromString,
                _registered_method=True)


class ScheduleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextTakings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSchedule,
                    request_deserializer=gRPC_dot_schedule__pb2.ScheduleRequest.FromString,
                    response_serializer=gRPC_dot_schedule__pb2.ScheduleResponse.SerializeToString,
            ),
            'GetSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedule,
                    request_deserializer=gRPC_dot_schedule__pb2.GetScheduleRequest.FromString,
                    response_serializer=gRPC_dot_schedule__pb2.GetScheduleResponse.SerializeToString,
            ),
            'GetSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedules,
                    request_deserializer=gRPC_dot_schedule__pb2.GetSchedulesRequest.FromString,
                    response_serializer=gRPC_dot_schedule__pb2.GetSchedulesResponse.SerializeToString,
            ),
            'GetNextTakings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextTakings,
                    request_deserializer=gRPC_dot_schedule__pb2.NextTakingsRequest.FromString,
                    response_serializer=gRPC_dot_schedule__pb2.NextTakingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'schedule.ScheduleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('schedule.ScheduleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScheduleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.ScheduleService/AddSchedule',
            gRPC_dot_schedule__pb2.ScheduleRequest.SerializeToString,
            gRPC_dot_schedule__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.ScheduleService/GetSchedule',
            gRPC_dot_schedule__pb2.GetScheduleRequest.SerializeToString,
            gRPC_dot_schedule__pb2.GetScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.ScheduleService/GetSchedules',
            gRPC_dot_schedule__pb2.GetSchedulesRequest.SerializeToString,
            gRPC_dot_schedule__pb2.GetSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextTakings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.ScheduleService/GetNextTakings',
            gRPC_dot_schedule__pb2.NextTakingsRequest.SerializeToString,
            gRPC_dot_schedule__pb2.NextTakingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
