# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gRPC/schedule.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gRPC/schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gRPC/schedule.proto\x12\x08schedule\"g\n\x11\x44\x61taOfUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nname_pills\x18\x02 \x01(\t\x12\x17\n\x0flimitation_days\x18\x03 \x01(\x05\x12\x14\n\x0cnumber_iters\x18\x04 \x01(\x05\"n\n\x16UserReturnScheduleData\x12\x17\n\x0fname_medication\x18\x01 \x01(\t\x12\x11\n\tfirst_day\x18\x02 \x01(\t\x12\x10\n\x08last_day\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x61ily_schedule\x18\x04 \x03(\t\"3\n\x18ReturnUserActualSchedule\x12\x17\n\x0fname_medication\x18\x01 \x01(\t\"<\n\x0fScheduleRequest\x12)\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1b.schedule.DataOfUserRequest\"4\n\x10ScheduleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x12GetScheduleRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x13\n\x0bschedule_id\x18\x02 \x01(\x05\"I\n\x13GetScheduleResponse\x12\x32\n\x08schedule\x18\x01 \x01(\x0b\x32 .schedule.UserReturnScheduleData\"&\n\x13GetSchedulesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"K\n\x14GetSchedulesResponse\x12\x33\n\tschedules\x18\x01 \x03(\x0b\x32 .schedule.UserReturnScheduleData\"%\n\x12NextTakingsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"O\n\x13NextTakingsResponse\x12\x38\n\x0cnext_takings\x18\x01 \x03(\x0b\x32\".schedule.ReturnUserActualSchedule\"\x07\n\x05\x45mpty2\xc1\x02\n\x0fScheduleService\x12\x44\n\x0b\x41\x64\x64Schedule\x12\x19.schedule.ScheduleRequest\x1a\x1a.schedule.ScheduleResponse\x12J\n\x0bGetSchedule\x12\x1c.schedule.GetScheduleRequest\x1a\x1d.schedule.GetScheduleResponse\x12M\n\x0cGetSchedules\x12\x1d.schedule.GetSchedulesRequest\x1a\x1e.schedule.GetSchedulesResponse\x12M\n\x0eGetNextTakings\x12\x1c.schedule.NextTakingsRequest\x1a\x1d.schedule.NextTakingsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC.schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAOFUSERREQUEST']._serialized_start=33
  _globals['_DATAOFUSERREQUEST']._serialized_end=136
  _globals['_USERRETURNSCHEDULEDATA']._serialized_start=138
  _globals['_USERRETURNSCHEDULEDATA']._serialized_end=248
  _globals['_RETURNUSERACTUALSCHEDULE']._serialized_start=250
  _globals['_RETURNUSERACTUALSCHEDULE']._serialized_end=301
  _globals['_SCHEDULEREQUEST']._serialized_start=303
  _globals['_SCHEDULEREQUEST']._serialized_end=363
  _globals['_SCHEDULERESPONSE']._serialized_start=365
  _globals['_SCHEDULERESPONSE']._serialized_end=417
  _globals['_GETSCHEDULEREQUEST']._serialized_start=419
  _globals['_GETSCHEDULEREQUEST']._serialized_end=477
  _globals['_GETSCHEDULERESPONSE']._serialized_start=479
  _globals['_GETSCHEDULERESPONSE']._serialized_end=552
  _globals['_GETSCHEDULESREQUEST']._serialized_start=554
  _globals['_GETSCHEDULESREQUEST']._serialized_end=592
  _globals['_GETSCHEDULESRESPONSE']._serialized_start=594
  _globals['_GETSCHEDULESRESPONSE']._serialized_end=669
  _globals['_NEXTTAKINGSREQUEST']._serialized_start=671
  _globals['_NEXTTAKINGSREQUEST']._serialized_end=708
  _globals['_NEXTTAKINGSRESPONSE']._serialized_start=710
  _globals['_NEXTTAKINGSRESPONSE']._serialized_end=789
  _globals['_EMPTY']._serialized_start=791
  _globals['_EMPTY']._serialized_end=798
  _globals['_SCHEDULESERVICE']._serialized_start=801
  _globals['_SCHEDULESERVICE']._serialized_end=1122
# @@protoc_insertion_point(module_scope)
