# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-04-21T20:54:06+00:00

from __future__ import annotations

from datetime import date, time
from typing import List, Optional

from pydantic import BaseModel, Field, conint


class DataOfUserRequest(BaseModel):
    user_id: int = Field(..., description='ID пользователя')
    name_pills: str = Field(..., description='Название лекарства')
    limitation_days: conint(ge=1) = Field(
        ...,
        description='Сколько дней составлять расписание',
    )
    number_iters: int = Field(
        ..., description='Сколько приёмов лекарства в день'
    )


class UserReturnScheduleData(BaseModel):
    name_medication: str = Field(..., description='Название лекарства')
    first_day: date = Field(..., description='Название лекарства')
    limitation_days: Optional[conint(ge=1)] = Field(
        None,
        description='Сколько дней составлять расписание',
    )
    daily_schedule: List[time] = Field(
        ..., description='Сколько приёмов лекарства в день'
    )


class ReturnUserActualSchedule(BaseModel):
    name_medication: str = Field(..., description='Название лекарства')
